services:
  weblu-api:
    container_name: weblu-api
    build:
      context: .
      dockerfile: dockerfile
    dns:
      - 8.8.8.8
    ports:
      - "5000:8080"
    env_file:
      - .env
    depends_on:
      - weblu-sqlserver
    volumes:
      - ./src/Weblu.Api/wwwroot:/app/wwwroot
  weblu-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1435:1433"
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - weblu-sql-server-volume:/var/opt/mssql
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_FIRSTRUN_ADMINPASSWORD}
    volumes:
      - seq-data:/data

volumes:
  weblu-sql-server-volume:
  seq-data:
    external: false 
